#!/bin/bash

set -e

source /dev/shm/sr-shelter-sync.env

cp /dev/shm/sr-client-secret.json ./client_secret.json
cp /dev/shm/sr-shelter-sync.token.json ./sheets.googleapis.com-santa-rosa-map.json

set -vx

node index.js -p ${PASSWORD} -u ${USERNAME} -t ${API_TOKEN}
